export const itemsArr = [
    {productName: 'Sneakers',
        store: 'Adidas',
        address: 'Krylatskaya street',
        category: 'sportswear',
        creationDate: '05.07.2021',
        price: '$1 000',
        remains: 40,
        weightVolume: '5kg'
    },
    {productName: 'Speakers',
        store: 'Sadida',
        address: 'Street Krylatskaya',
        category: 'Wear Sports',
        creationDate: '2025.11.30',
        price: '7000 $',
        remains: 5,
        weightVolume: '2kg'
    },
    {productName: 'Fleekers',
        store: 'Carabia',
        address: 'Moslovskaya street',
        category: 'snowboarding',
        creationDate: '30.05.2022',
        price: '17300 %',
        remains: 55,
        weightVolume: '20kg'
    },
    {productName: 'Fleekers',
        store: 'Carabia',
        address: 'Moslovskaya street',
        category: 'snowboarding',
        creationDate: '30.05.2022',
        price: '17300 %',
        remains: 55,
        weightVolume: '20kg'
    },{productName: 'Fleekers',
        store: 'Carabia',
        address: 'Moslovskaya street',
        category: 'snowboarding',
        creationDate: '30.05.2022',
        price: '17300 %',
        remains: 55,
        weightVolume: '20kg'
    },{productName: 'Fleekers',
        store: 'Carabia',
        address: 'Moslovskaya street',
        category: 'snowboarding',
        creationDate: '30.05.2022',
        price: '17300 %',
        remains: 55,
        weightVolume: '20kg'
    },
    {productName: 'Sneakers',
        store: 'Adidas',
        address: 'Krylatskaya street',
        category: 'sportswear',
        creationDate: '05.07.2021',
        price: '$1 000',
        remains: 40,
        weightVolume: '5kg'
    },
    {productName: 'Speakers',
        store: 'Sadida',
        address: 'Street Krylatskaya',
        category: 'Wear Sports',
        creationDate: '2025.11.30',
        price: '7000 $',
        remains: 5,
        weightVolume: '2kg'
    },
    {productName: 'Fleekers',
        store: 'Carabia',
        address: 'Moslovskaya street',
        category: 'snowboarding',
        creationDate: '30.05.2022',
        price: '17300 %',
        remains: 55,
        weightVolume: '20kg'
    },
    {productName: 'Fleekers',
        store: 'Carabia',
        address: 'Moslovskaya street',
        category: 'snowboarding',
        creationDate: '30.05.2022',
        price: '17300 %',
        remains: 55,
        weightVolume: '20kg'
    },{productName: 'Fleekers',
        store: 'Carabia',
        address: 'Moslovskaya street',
        category: 'snowboarding',
        creationDate: '30.05.2022',
        price: '17300 %',
        remains: 55,
        weightVolume: '20kg'
    },{productName: 'Fleekers',
        store: 'Carabia',
        address: 'Moslovskaya street',
        category: 'snowboarding',
        creationDate: '30.05.2022',
        price: '17300 %',
        remains: 55,
        weightVolume: '20kg'
    },
];



