export const itemsArr = [];

// export const itemsArr = [
//     {productName: 'Sneakers',
//         store: 'Adidas',
//         address: 'Krylatskaya street',
//         category: 'sportswear',
//         creationDate: '05.07.2021',
//         price: '$1 000',
//         remains: 40,
//         weightVolume: '5kg',
//         id: '01',
//
//     },
//     {productName: 'Speakers',
//         store: 'Sadida',
//         address: 'Street Krylatskaya',
//         category: 'Wear Sports',
//         creationDate: '2025.11.30',
//         price: '7000 $',
//         remains: 5,
//         weightVolume: '2kg',
//         id: '02',
//
//     },
//     {productName: 'Fleekers',
//         store: 'Carabia',
//         address: 'Moslovskaya street',
//         category: 'snowboarding',
//         creationDate: '30.05.2022',
//         price: '17300 %',
//         remains: 55,
//         weightVolume: '20kg',
//         id: '03',
//
//     },
//     {productName: 'Fleekers',
//         store: 'Carabia',
//         address: 'Moslovskaya street',
//         category: 'snowboarding',
//         creationDate: '30.05.2022',
//         price: '17300 %',
//         remains: 55,
//         weightVolume: '20kg',
//         id: '04',
//
//     },{productName: 'Fleekers',
//         store: 'Carabia',
//         address: 'Moslovskaya street',
//         category: 'snowboarding',
//         creationDate: '30.05.2022',
//         price: '17300 %',
//         remains: 55,
//         weightVolume: '20kg',
//         id: '05',
//
//     },{productName: 'Fleekers',
//         store: 'Carabia',
//         address: 'Moslovskaya street',
//         category: 'snowboarding',
//         creationDate: '30.05.2022',
//         price: '17300 %',
//         remains: 55,
//         weightVolume: '20kg',
//         id: '06',
//
//     },
//     {productName: 'Sneakers',
//         store: 'Adidas',
//         address: 'Krylatskaya street',
//         category: 'sportswear',
//         creationDate: '05.07.2021',
//         price: '$1 000',
//         remains: 40,
//         weightVolume: '5kg',
//         id: '07',
//
//     },
//     {productName: 'Speakers',
//         store: 'Sadida',
//         address: 'Street Krylatskaya',
//         category: 'Wear Sports',
//         creationDate: '2025.11.30',
//         price: '7000 $',
//         remains: 5,
//         weightVolume: '2kg',
//         id: '08',
//
//     },
//     {productName: 'Fleekers',
//         store: 'Carabia',
//         address: 'Moslovskaya street',
//         category: 'snowboarding',
//         creationDate: '30.05.2022',
//         price: '17300 %',
//         remains: 55,
//         weightVolume: '20kg',
//         id: '09',
//
//     },
//     {productName: 'Fleekers',
//         store: 'Carabia',
//         address: 'Moslovskaya street',
//         category: 'snowboarding',
//         creationDate: '30.05.2022',
//         price: '17300 %',
//         remains: 55,
//         weightVolume: '20kg',
//         id: '10',
//
//     },{productName: 'Fleekers',
//         store: 'Carabia',
//         address: 'Moslovskaya street',
//         category: 'snowboarding',
//         creationDate: '30.05.2022',
//         price: '17300 %',
//         remains: 55,
//         weightVolume: '20kg',
//         id: '11',
//
//     },{productName: 'Fleekers',
//         store: 'Carabia',
//         address: 'Moslovskaya street',
//         category: 'snowboarding',
//         creationDate: '30.05.2022',
//         price: '17300 %',
//         remains: 55,
//         weightVolume: '20kg',
//         id: '12',
//
//     },
// ];
//
//
//
